name: Mobydick Action
description: GitHub Action to validate that Docker images are compatible with Dependabot's update strategy.
branding:
  icon: anchor
  color: blue
runs:
  using: docker
  image: Dockerfile
